import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMemberStatus1778708618094 implements MigrationInterface {
    name = 'AddMemberStatus1778708618094'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_leader_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cae_managers" DROP CONSTRAINT "cae_managers_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cae_managers" DROP CONSTRAINT "cae_managers_cae_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "caes" DROP CONSTRAINT "caes_state_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "cars_cae_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP CONSTRAINT "universities_city_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP CONSTRAINT "member_courses_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP CONSTRAINT "member_courses_course_university_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "course_universities_university_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "course_universities_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "course_universities_city_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP CONSTRAINT "FK_1229b56aa12cae674b824fccd13"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "members_registration_reviewed_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "members_sponsor_fkey"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_fb20efab0b958b100aa5f6aaa52"`);
        await queryRunner.query(`ALTER TABLE "project_tasks" DROP CONSTRAINT "project_tasks_project_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "token" DROP CONSTRAINT "memberId"`);
        await queryRunner.query(`ALTER TABLE "course_managers" DROP CONSTRAINT "course_managers_member_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_managers" DROP CONSTRAINT "course_managers_course_university_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "car_cities" DROP CONSTRAINT "FK_d36d35258adbd7e18a9834c2368"`);
        await queryRunner.query(`ALTER TABLE "car_cities" DROP CONSTRAINT "FK_aa73603ec9edea7e90ca7b6c238"`);
        await queryRunner.query(`ALTER TABLE "car_managers" DROP CONSTRAINT "FK_bc69c853b186d6d39e13792a405"`);
        await queryRunner.query(`ALTER TABLE "car_managers" DROP CONSTRAINT "FK_3f4ffe42d4a3d8c9ee9afb481bd"`);
        await queryRunner.query(`ALTER TABLE "member_roles" DROP CONSTRAINT "FK_e9080e7a7997a0170026d5139c1"`);
        await queryRunner.query(`ALTER TABLE "member_roles" DROP CONSTRAINT "FK_d2a7fdeb2a87338df1362a0bfbf"`);
        await queryRunner.query(`DROP INDEX "public"."universities_emec_code_key"`);
        await queryRunner.query(`DROP INDEX "public"."course_universities_course_university_city_key"`);
        await queryRunner.query(`DROP INDEX "public"."course_universities_external_course_id_idx"`);
        await queryRunner.query(`DROP INDEX "public"."cities_ibge_code_key"`);
        await queryRunner.query(`DROP INDEX "public"."members_registration_status_idx"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "members_registration_status_check"`);
        await queryRunner.query(`ALTER TABLE "cae_managers" DROP CONSTRAINT "cae_managers_cae_id_member_id_key"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP CONSTRAINT "member_courses_member_id_course_university_id_key"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "course_universities_course_id_university_id_city_id_key"`);
        await queryRunner.query(`ALTER TABLE "course_managers" DROP CONSTRAINT "course_managers_course_university_id_member_id_key"`);
        await queryRunner.query(`CREATE TYPE "public"."project_task_responsible_status_enum" AS ENUM('Pendente', 'Aceito', 'Recusado')`);
        await queryRunner.query(`CREATE TABLE "project_task_responsible" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "member_id" uuid NOT NULL, "status" "public"."project_task_responsible_status_enum" NOT NULL DEFAULT 'Pendente', CONSTRAINT "PK_72546846b00fff9f33da2e88603" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "member_skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "member_id" uuid NOT NULL, "skill_id" uuid NOT NULL, "data_add" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b64abd61ad6150e9a305a2eec84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."goal_goal_type_enum" AS ENUM('Aquisição de membros', 'Participar de Projetos', 'Presença em reuniões')`);
        await queryRunner.query(`CREATE TABLE "goal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(255) NOT NULL, "description" text NOT NULL, "goal_type" "public"."goal_goal_type_enum" NOT NULL, "parameter" integer NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "creator_id" uuid NOT NULL, CONSTRAINT "PK_88c8e2b461b711336c836b1e130" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."skills_status"`);
        await queryRunner.query(`ALTER TABLE "states" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "city_id"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "emec_code"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "universities" DROP COLUMN "organization_type"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "external_course_id"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "source"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "degree_type"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "modality"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP COLUMN "academic_level"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "creation_date"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "current_semester"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "university_not_applicable"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "course_not_applicable"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "current_semester_not_applicable"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "registration_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "registration_reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "registration_status"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "registration_rejection_reason"`);
        await queryRunner.query(`ALTER TABLE "members" ADD "status" character varying(20) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id")`);
        await queryRunner.query(`ALTER TABLE "car_cities" ADD CONSTRAINT "PK_79feb47d808448046bfc78dc511" PRIMARY KEY ("car_id", "city_id")`);
        await queryRunner.query(`ALTER TABLE "car_managers" ADD CONSTRAINT "PK_317cadf28edd1356d3b09a8447f" PRIMARY KEY ("car_id", "member_id")`);
        await queryRunner.query(`ALTER TABLE "member_roles" ADD CONSTRAINT "PK_9a7d914e0a37c2cacabb47d4555" PRIMARY KEY ("member_id", "role_id")`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "leader_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "is_selective" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "done" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "skills_name_key"`);
        await queryRunner.query(`ALTER TABLE "cae_managers" ALTER COLUMN "start_date" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "course_university_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."enum_member_course_status" RENAME TO "enum_member_course_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."member_courses_status_enum" AS ENUM('active', 'suspended', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "status" TYPE "public"."member_courses_status_enum" USING "status"::"text"::"public"."member_courses_status_enum"`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."enum_member_course_status_old"`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "started_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ALTER COLUMN "project_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ALTER COLUMN "is_open" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ALTER COLUMN "done" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "course_managers" ALTER COLUMN "start_date" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa73603ec9edea7e90ca7b6c23" ON "car_cities" ("car_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d36d35258adbd7e18a9834c236" ON "car_cities" ("city_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f4ffe42d4a3d8c9ee9afb481b" ON "car_managers" ("car_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc69c853b186d6d39e13792a40" ON "car_managers" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2a7fdeb2a87338df1362a0bfb" ON "member_roles" ("member_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9080e7a7997a0170026d5139c" ON "member_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "cae_managers" ADD CONSTRAINT "FK_5ebeb99a4670d782168f91732fe" FOREIGN KEY ("cae_id") REFERENCES "caes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cae_managers" ADD CONSTRAINT "FK_182cf230db1e6fb668801ee43d2" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caes" ADD CONSTRAINT "FK_8c507b1d6a72c407fe65910512b" FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "FK_269b6c6d06fdbd924ecc702a921" FOREIGN KEY ("cae_id") REFERENCES "caes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD CONSTRAINT "FK_7bc2d70217af9c2a6fe1ad15d52" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD CONSTRAINT "FK_44285bdba51a3653c5b7018a0ff" FOREIGN KEY ("course_university_id") REFERENCES "course_universities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "FK_a01a645e9c95fe8d59ee4c7387c" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "FK_5a5ec47fa58e5e01f02c035254a" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "FK_636b545071e993d1455ed47aa33" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cities" ADD CONSTRAINT "FK_1229b56aa12cae674b824fccd13" FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_fb20efab0b958b100aa5f6aaa52" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_managers" ADD CONSTRAINT "FK_01c2af57c5f04b18e55d761a555" FOREIGN KEY ("course_university_id") REFERENCES "course_universities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_managers" ADD CONSTRAINT "FK_5deae70df0743c08eafbe373979" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_cities" ADD CONSTRAINT "FK_aa73603ec9edea7e90ca7b6c238" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "car_cities" ADD CONSTRAINT "FK_d36d35258adbd7e18a9834c2368" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_managers" ADD CONSTRAINT "FK_3f4ffe42d4a3d8c9ee9afb481bd" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "car_managers" ADD CONSTRAINT "FK_bc69c853b186d6d39e13792a405" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_roles" ADD CONSTRAINT "FK_d2a7fdeb2a87338df1362a0bfbf" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "member_roles" ADD CONSTRAINT "FK_e9080e7a7997a0170026d5139c1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "member_roles" DROP CONSTRAINT "FK_e9080e7a7997a0170026d5139c1"`);
        await queryRunner.query(`ALTER TABLE "member_roles" DROP CONSTRAINT "FK_d2a7fdeb2a87338df1362a0bfbf"`);
        await queryRunner.query(`ALTER TABLE "car_managers" DROP CONSTRAINT "FK_bc69c853b186d6d39e13792a405"`);
        await queryRunner.query(`ALTER TABLE "car_managers" DROP CONSTRAINT "FK_3f4ffe42d4a3d8c9ee9afb481bd"`);
        await queryRunner.query(`ALTER TABLE "car_cities" DROP CONSTRAINT "FK_d36d35258adbd7e18a9834c2368"`);
        await queryRunner.query(`ALTER TABLE "car_cities" DROP CONSTRAINT "FK_aa73603ec9edea7e90ca7b6c238"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "course_managers" DROP CONSTRAINT "FK_5deae70df0743c08eafbe373979"`);
        await queryRunner.query(`ALTER TABLE "course_managers" DROP CONSTRAINT "FK_01c2af57c5f04b18e55d761a555"`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "FK_fb20efab0b958b100aa5f6aaa52"`);
        await queryRunner.query(`ALTER TABLE "cities" DROP CONSTRAINT "FK_1229b56aa12cae674b824fccd13"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "FK_636b545071e993d1455ed47aa33"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "FK_5a5ec47fa58e5e01f02c035254a"`);
        await queryRunner.query(`ALTER TABLE "course_universities" DROP CONSTRAINT "FK_a01a645e9c95fe8d59ee4c7387c"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP CONSTRAINT "FK_44285bdba51a3653c5b7018a0ff"`);
        await queryRunner.query(`ALTER TABLE "member_courses" DROP CONSTRAINT "FK_7bc2d70217af9c2a6fe1ad15d52"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "FK_269b6c6d06fdbd924ecc702a921"`);
        await queryRunner.query(`ALTER TABLE "caes" DROP CONSTRAINT "FK_8c507b1d6a72c407fe65910512b"`);
        await queryRunner.query(`ALTER TABLE "cae_managers" DROP CONSTRAINT "FK_182cf230db1e6fb668801ee43d2"`);
        await queryRunner.query(`ALTER TABLE "cae_managers" DROP CONSTRAINT "FK_5ebeb99a4670d782168f91732fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9080e7a7997a0170026d5139c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2a7fdeb2a87338df1362a0bfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc69c853b186d6d39e13792a40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f4ffe42d4a3d8c9ee9afb481b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d36d35258adbd7e18a9834c236"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa73603ec9edea7e90ca7b6c23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`ALTER TABLE "course_managers" ALTER COLUMN "start_date" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "token" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "token" ALTER COLUMN "createdAt" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token" ALTER COLUMN "type" SET DEFAULT 'access'`);
        await queryRunner.query(`ALTER TABLE "token" DROP COLUMN "memberId"`);
        await queryRunner.query(`ALTER TABLE "token" ADD "memberId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "token" ADD "token" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ALTER COLUMN "done" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ALTER COLUMN "is_open" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ALTER COLUMN "project_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "biography"`);
        await queryRunner.query(`ALTER TABLE "members" ADD "biography" character varying(2600)`);
        await queryRunner.query(`ALTER TABLE "members" DROP CONSTRAINT "UQ_c18138114a46a258e384c673606"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "ra"`);
        await queryRunner.query(`ALTER TABLE "members" ADD "ra" character varying(40) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "members" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "started_at" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`CREATE TYPE "public"."enum_member_course_status_old" AS ENUM('active', 'suspended', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "status" TYPE "public"."enum_member_course_status_old" USING "status"::"text"::"public"."enum_member_course_status_old"`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."member_courses_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."enum_member_course_status_old" RENAME TO "enum_member_course_status"`);
        await queryRunner.query(`ALTER TABLE "member_courses" ALTER COLUMN "course_university_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cae_managers" ALTER COLUMN "start_date" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "skills_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "done" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "is_selective" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "projects" ALTER COLUMN "leader_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "member_roles" DROP CONSTRAINT "PK_9a7d914e0a37c2cacabb47d4555"`);
        await queryRunner.query(`ALTER TABLE "car_managers" DROP CONSTRAINT "PK_317cadf28edd1356d3b09a8447f"`);
        await queryRunner.query(`ALTER TABLE "car_cities" DROP CONSTRAINT "PK_79feb47d808448046bfc78dc511"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "PK_25d24010f53bb80b78e412c9656"`);
        await queryRunner.query(`ALTER TABLE "members" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "members" ADD "registration_rejection_reason" text`);
        await queryRunner.query(`ALTER TABLE "members" ADD "registration_status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "members" ADD "registration_reviewed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "members" ADD "registration_reviewed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "members" ADD "current_semester_not_applicable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "members" ADD "course_not_applicable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "members" ADD "university_not_applicable" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "members" ADD "current_semester" integer`);
        await queryRunner.query(`ALTER TABLE "members" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "members" ADD "creation_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "cities" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "academic_level" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "modality" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "degree_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "source" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "external_course_id" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "organization_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "category" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "source" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "emec_code" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "status" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "city_id" uuid`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "universities" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "states" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`CREATE TYPE "public"."skills_status" AS ENUM('Pendente', 'Aprovado')`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "status" "public"."skills_status" NOT NULL DEFAULT 'Pendente'`);
        await queryRunner.query(`DROP TABLE "goal"`);
        await queryRunner.query(`DROP TYPE "public"."goal_goal_type_enum"`);
        await queryRunner.query(`DROP TABLE "member_skill"`);
        await queryRunner.query(`DROP TABLE "project_task_responsible"`);
        await queryRunner.query(`DROP TYPE "public"."project_task_responsible_status_enum"`);
        await queryRunner.query(`ALTER TABLE "course_managers" ADD CONSTRAINT "course_managers_course_university_id_member_id_key" UNIQUE ("course_university_id", "member_id")`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "course_universities_course_id_university_id_city_id_key" UNIQUE ("course_id", "university_id", "city_id")`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD CONSTRAINT "member_courses_member_id_course_university_id_key" UNIQUE ("member_id", "course_university_id")`);
        await queryRunner.query(`ALTER TABLE "cae_managers" ADD CONSTRAINT "cae_managers_cae_id_member_id_key" UNIQUE ("cae_id", "member_id")`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "members_registration_status_check" CHECK (((registration_status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "members_registration_status_idx" ON "members" ("registration_status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "cities_ibge_code_key" ON "cities" ("ibge_code") WHERE (ibge_code IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "course_universities_external_course_id_idx" ON "course_universities" ("external_course_id") WHERE (external_course_id IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "course_universities_course_university_city_key" ON "course_universities" ("city_id", "course_id", "university_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "universities_emec_code_key" ON "universities" ("emec_code") WHERE (emec_code IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "member_roles" ADD CONSTRAINT "FK_d2a7fdeb2a87338df1362a0bfbf" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_roles" ADD CONSTRAINT "FK_e9080e7a7997a0170026d5139c1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_managers" ADD CONSTRAINT "FK_3f4ffe42d4a3d8c9ee9afb481bd" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_managers" ADD CONSTRAINT "FK_bc69c853b186d6d39e13792a405" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_cities" ADD CONSTRAINT "FK_aa73603ec9edea7e90ca7b6c238" FOREIGN KEY ("car_id") REFERENCES "cars"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "car_cities" ADD CONSTRAINT "FK_d36d35258adbd7e18a9834c2368" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_managers" ADD CONSTRAINT "course_managers_course_university_id_fkey" FOREIGN KEY ("course_university_id") REFERENCES "course_universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_managers" ADD CONSTRAINT "course_managers_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "token" ADD CONSTRAINT "memberId" FOREIGN KEY ("memberId") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_tasks" ADD CONSTRAINT "project_tasks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "FK_fb20efab0b958b100aa5f6aaa52" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "members_sponsor_fkey" FOREIGN KEY ("sponsor") REFERENCES "members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "members" ADD CONSTRAINT "members_registration_reviewed_by_fkey" FOREIGN KEY ("registration_reviewed_by") REFERENCES "members"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cities" ADD CONSTRAINT "FK_1229b56aa12cae674b824fccd13" FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "course_universities_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "course_universities_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_universities" ADD CONSTRAINT "course_universities_university_id_fkey" FOREIGN KEY ("university_id") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD CONSTRAINT "member_courses_course_university_id_fkey" FOREIGN KEY ("course_university_id") REFERENCES "course_universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "member_courses" ADD CONSTRAINT "member_courses_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "universities" ADD CONSTRAINT "universities_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "cars_cae_id_fkey" FOREIGN KEY ("cae_id") REFERENCES "caes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "caes" ADD CONSTRAINT "caes_state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "states"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cae_managers" ADD CONSTRAINT "cae_managers_cae_id_fkey" FOREIGN KEY ("cae_id") REFERENCES "caes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cae_managers" ADD CONSTRAINT "cae_managers_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_leader_id_fkey" FOREIGN KEY ("leader_id") REFERENCES "members"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
